# Generated by Django 5.2.6 on 2025-10-08 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.ImageField(upload_to='')),
                ('Name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phon_number', models.IntegerField()),
                ('designation', models.CharField(max_length=100)),
                ('salary', models.IntegerField()),
                ('image', models.ImageField(upload_to='images')),
            ],
        ),
    ]
